application: p3proj
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: .*/video
  script: video.php

- url: .*/profile
  script: profile.html

- url: .*
  script: psych100btest.php